# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michael Duergner
url:              https://duergner.github.io
paginate:         1
baseurl:          /
author:
  name:           Michael Duergner
  url:            https://duergner.github.io
  email:          michael@sprucehill.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/duergner/duergner.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'