# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Duergner
url:              https://michael.duergner.com
paginate:         1
baseurl:          /
author:
  name:           Michael Duergner
  url:            https://michael.duergner.com
  email:          michael@duergner.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/duergner/duergner.github.io

pages_list:
  About: '/about'
  Talks: '/talks'
  Archive: '/archive'
  Feed: '/atom.xml'
